name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # Buildozer works well with 3.8-3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        pip install cython  # Required for compilation

    - name: Accept Android SDK licenses (backup for non-interactive env)
      run: |
        # Install SDK tools minimally
        mkdir -p ~/.buildozer/android/platform
        echo y | sdkmanager --licenses || true  # Ignore if not present yet

    - name: Cache Buildozer
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          .buildozer_android_platform
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Build APK
      run: |
        buildozer android debug
      env:
        ANDROID_SDK_ROOT: ~/.buildozer/android/platform/android-sdk
        ANDROID_NDK_ROOT: ~/.buildozer/android/platform/android-ndk

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-debug.apk
        path: bin/myapp-0.1-debug.apk  # Adjust path if your version differs
        retention-days: 30
